---
title: "chapter 5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rstan)
options(mc.cores = parallel::detectCores()-1) ## for parallel computing 
library(tidyverse)
library(ggplot2)
library(GGally)
library(here)
library(ggmcmc)
```


```{r}
attend <- read.csv(here("code/ch.5/input/data-attendance-1.txt"))
## A : satisfied with a part-time job
## Score : the score how much interested with in a study
## Y : the attendance rate for a year.
```

```{r}
ggpairs(attend) 
```

## fit a multivariate regression model
```{r}
data = list(N = nrow(attend), 
            A = attend$A, 
            Score = attend$Score/200, # scaling for a converge
            Y = attend$Y)

fit = stan(file = here("source", "chpt 5", "model5-3.stan"),
           data = data,
           seed = 1234)

save.image(here("output", "chpt5", "result-model5-3.RData"))
```

```{r}
fit
```

```{r}
ggmcmc(ggs(fit), file = here("output/chpt5", "fit-ggmcmc.pdf"))

```

## binary logistic regression

```{r}
d <- read.csv(here("code/ch.5/input/data-attendance-2.txt"))
## PersonID : students ID
## M : total number of classes that enrolled as a 3-month course.
## Y : a number of Attendance actually
## A : satisfied with a part-time job
## Score : the score how much interested with in a study
str(d)
```

```{r}
data = list(N = nrow(d),
            A = d$A,
            M = d$M,
            Score = d$Score/200, 
            Y = d$Y)
fit = stan(file=here("source", "chpt 5", "model5-4.stan"),
           data = data, seed = 1234)
```

```{r}
fit
```

```{r}
save.image(here("output", "chpt5", "result-model5-4.RData"))
```

```{r}
ggmcmc(ggs(fit), file = here("output/chpt5", "fit-ggmcmc2.pdf"))
```


#### logistic regression
```{r}
d <- read.csv(here("code/ch.5/input/data-attendance-3.txt"))
str(d)

## PersonID : students ID
## Y : Attendance actually: 0 - absent / 1 - present
## A : satisfied with a part-time job
## Score : the score how much interested with in a study
## Weather : A : sunny, B : cloudy, C : rainy
```

```{r}
table(d$Weather, d$Y)
```


```{r}
conv = c(0, 0.2, 1)

names(conv) = c("A", "B", "C")

data = list( 
  I = nrow(d),
  Score = d$Score/200,
  A = d$A,
  W = conv[d$Weather],
  Y = d$Y
)

fit = stan(file = here("source/chpt 5/model5-5b.stan"),
           data = data,
           seed = 1234)
```
```{r}
fit
ggmcmc(ggs(fit),here("output/chpt5/fit-ggmcmc3.pdf"))
```

#### Poisson regression

```{r}
d <- read.csv(here("code/ch.5/input/data-attendance-2.txt"))
## PersonID : students ID
## M : total number of classes that enrolled as a 3-month course.
## Y : a number of Attendance actually
## A : satisfied with a part-time job
## Score : the score how much interested with in a study
str(d)
```

```{r}
data = list(
  N = nrow(d),
  A = d$A,
  Score = d$Score/200,
  M = d$M,
  Y = d$Y
)

fit = stan(file = here("source/chpt 5/model5-6b.stan"),
           data=data,
           seed = 1234)

```
```{r}
fit
```

