---
title: "Chapter 4"
output: html_document
number_sections: true
toc: true
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy=T)
```

```{r}
library(tidyverse)
library(ggplot2)
library(rstan)
library(ggmcmc)
```


## simple regression
```{r}
salary <- read.csv("../code/ch.4/input/data-salary.txt")
```

```{r}
plot(salary)
```
```{r}
salary %>% ggplot(aes(x=X, y=Y)) + geom_point()
```

### model equation
- standard
$$\begin{eqnarray}
Y[n] & = & \mathcal{y}_{base}[n] + \varepsilon [n] \qquad & n = 1,2, \cdots , N \\
\mathcal{y}_{base}[n] &=& a + b X[n] \quad \quad & n = 1,2, \cdots , N\\
\varepsilon [n] &\sim& Normal(0, \sigma) \qquad & n = 1,2, \cdots , N
\end{eqnarray}$$

- simple
$$\begin{eqnarray}
\mathcal{y}_{base}[n] & = & a + b X[n] \quad \quad & n = 1,2, \cdots , N\\
Y [n] &\sim& Normal(\mathcal{y}_{base}[n], \sigma) \qquad & n = 1,2, \cdots , N
\end{eqnarray}$$

$$\begin{eqnarray}
\mathcal{y}_{base}[n] &=& a + b X[n] \quad \quad & n = 1,2, \cdots , N\\
Y [n] &\sim& Normal(\mathcal{y}_{base}[n], \sigma) \qquad & n = 1,2, \cdots , N
\end{eqnarray}$$

$$\begin{eqnarray}
Y[n] &\sim& Normal(\mathcal{y}_{base}[n], \sigma) \qquad & n = 1,2, \cdots , N
\end{eqnarray}$$


```{r}
res_lm = lm(Y~X, data=salary)
res_lm
```

```{r}
data = list(N = nrow(salary), X = salary$X, Y = salary$Y)
fit = stan(file = "../source/model4-5.stan", data=data, seed=1234)
```

```{r}
fit
```


```{r}
ggmcmc(ggs(fit, inc_warmup = T, stan_include_auxiliar = T),
       file = "../output/fit-traceplot.pdf", plot='traceplot')

ggmcmc(ggs(fit), file = "../output/fit-ggmcmc.pdf")
```

## option in MCMC

```{r}
stanmodel = stan_model(file="./model4-5.stan")

fit_option = sampling(
  stanmodel, 
  data = data,
  pars = c("b", "sigma"),
  init = function(){
    list(a = runif(1, -10, 10),
         b = runif(1, 0, 10), 
         sigma = 10)
  },
  seed = 123,
  chains = 3, iter = 1000, warmup = 200, thin = 2
)

summary(fit_option)
?sampling
```

## to compute the chain with multi-cores
  - if use this option, fixing a bug is more difficult. After check the computation have no error, use it.
```{r}
rstan_options(auto_write = T)
options(mc.cores = parallel::detectCores())
```
  
```{r}
ms = rstan::extract(fit)
dim(ms$b)
quantile(ms$b, prob=c(0.025, 0.975))
```

```{r}
d_mcmc = data.frame(a = ms$a, b = ms$b, sigma = ms$sigma)
head(d_mcmc)
```

### generate new data with stan code
```{r}
X_new = 23:60

data = list = list(N=nrow(salary), X=salary$X, Y=salary$Y, N_new = length(X_new), X_new = X_new)

fit_new = stan(file="./model4-4.stan", data=data, seed=1234)

ms_new = rstan::extract(fit_new)

data.frame.quantile.mcmc = function(x, y_mcmc, 
                                    probs = c(2.5, 25, 50, 75, 97.5)/100) {
  qua = apply(y_mcmc, 2, quantile, probs = probs)
  d = data.frame(X=x, t(qua))
  colnames(d) = c("X", paste0('p', probs*100))
  return(d)
}

ggplot.5quantile = function(data) {
  p = ggplot(data=data, aes(x=X, y=p50)) + 
    theme_bw(base_size = 18) + 
    geom_ribbon(aes(ymin = p2.5, ymax = p97.5), fill = "black", alpha = 1/6) + 
    geom_ribbon(aes(ymin = p25, ymax = p75), fill = "black", alpha = 2/6) +
    geom_line(size = 1)
  return(p)
}

customize.ggplot.axis = function(p){
  p = p + labs(x = "X", y = "Y") + 
    scale_y_continuous(breaks = seq(from = 2000, to = 14000, by = 4000)) +
    coord_cartesian(xlim = c(22, 61), ylim = c(2000, 14000))
  return(p)
  
}

d_est = data.frame.quantile.mcmc(x = X_new, y_mcmc = ms_new$y_base_new)
p = ggplot.5quantile(data=d_est)
p = p + geom_point(data=d, aes(x=X, y=Y), shape = 1, size = 3) 
p = p + customize.ggplot.axis(p)
ggsave(file = "./output/fig4-8-left-2.png", plot = p, dpi = 300, w=4, h=3)

d_est = data.frame.quantile.mcmc(x = X_new, y_mcmc = ms_new$y_new)
p = ggplot.5quantile(data=d_est) 
p = p + geom_point(data=d, aes(x=X, y=Y), shape = 1, size = 3) 
p = p + customize.ggplot.axis(p)
ggsave(file = "./output/fig4-8-right-2.png", plot = p, dpi = 300, w=4, h=3)
  
```

